// src/app/layout.js
import './globals.css';
import { GeistSans } from 'geist/font/sans'; // ✅ CORRECTED FONT IMPORT
import { GeistMono } from 'geist/font/mono';   // ✅ CORRECTED FONT IMPORT


import { Toaster } from "../components/ui/sonner";
import BlendInvite from "../../components/SocketHandler"; // Using path alias for cleanliness
import { UserProvider } from '../../context/UserContext';   // Using path alias for cleanliness

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* ✅ CORRECTED FONT USAGE */}
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        <Toaster position="top-right" richColors />
        <UserProvider>
          <BlendInvite/>
          {children}
        </UserProvider>
      </body>
    </html>
  );
}